apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eclwatch-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - hpcc-ingress.eastus2.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: hpcc-ingress.eastus2.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
         service:
           name: eclwatch
           port:
             number: 8010
